# Generated by Django 4.2.16 on 2024-10-31 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocksubject',
            name='subject_ptr',
        ),
        migrations.AddField(
            model_name='stocksubject',
            name='subject',
            field=models.ForeignKey(default='5f5e12bd-2807-4ce8-a260-3405d68dc755', on_delete=django.db.models.deletion.CASCADE, to='schedule.subject'),
        ),
    ]
